2025-06-26 13:45:38,058 - PokeXHelper - INFO - PokeXGames Helper logging initialized
2025-06-26 13:45:38,236 - PokeXHelper - INFO - Initializing PokeXGames Helper
2025-06-26 13:45:38,238 - PokeXHelper - INFO - Components initialized successfully
2025-06-26 13:45:38,257 - PokeXHelper - INFO - PokeXGames Helper interface initialized
2025-06-26 13:45:38,261 - PokeXHelper - INFO - Configuration loaded from file
2025-06-26 13:45:38,261 - PokeXHelper - INFO - Selection configured from saved coordinates: (64,516) to (260,528)
2025-06-26 13:45:38,386 - PokeXHelper - INFO - Selection configured from saved coordinates: (3173,46) to (3436,366)
2025-06-26 13:45:38,483 - PokeXHelper - INFO - Selection configured from saved coordinates: (13,412) to (280,787)
2025-06-26 13:45:38,587 - PokeXHelper - INFO - Loaded 2 navigation steps
2025-06-26 13:45:38,594 - PokeXHelper - CRITICAL - Fatal error: 'InterfaceManager' object has no attribute 'check_configuration'
Traceback (most recent call last):
  File "C:\repositories\pxg-helper\pokexgames_helper.py", line 78, in main
    app = PokeXGamesHelper(root)
          ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\repositories\pxg-helper\app\gui\__init__.py", line 23, in __init__
    self.interface_manager.check_configuration()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'InterfaceManager' object has no attribute 'check_configuration'
